# Generated by Django 5.2.4 on 2025-07-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=125, verbose_name="SiteName")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="SiteDescription"
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        blank=True,
                        upload_to="logo_heder/%Y/%m/%d",
                        verbose_name="ImageHeader",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="0912xxxxxxxx",
                        max_length=11,
                        null=True,
                        verbose_name="NumberPhone",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, verbose_name="Email"
                    ),
                ),
                ("x", models.URLField(blank=True, null=True, verbose_name="X_Twitter")),
                (
                    "instagram",
                    models.URLField(blank=True, null=True, verbose_name="Instagram"),
                ),
                (
                    "telegram",
                    models.URLField(blank=True, null=True, verbose_name="Telegram"),
                ),
                (
                    "github",
                    models.URLField(blank=True, null=True, verbose_name="GitHub"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="CreationDate"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="LastUpdatedDate"),
                ),
            ],
            options={
                "verbose_name": "Setting Site",
                "verbose_name_plural": "Setting Site",
                "ordering": ["-created_at"],
            },
        ),
    ]
