# Generated by Django 5.2.4 on 2025-07-31 17:06

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/', validators=[accounts.validators.avatar_validator], verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, validators=[accounts.validators.phone_number_validator], verbose_name='Full Name'),
        ),
    ]
