# Generated by Django 4.2.20 on 2025-10-24 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_full_name_alter_customuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_posts', models.PositiveIntegerField(default=0, verbose_name='Total Posts')),
                ('total_likes_received', models.PositiveIntegerField(default=0, verbose_name='Total Likes Received')),
                ('total_comments_received', models.PositiveIntegerField(default=0, verbose_name='Total Comments Received')),
                ('total_views_received', models.PositiveIntegerField(default=0, verbose_name='Total Views Received')),
                ('total_bookmarks_received', models.PositiveIntegerField(default=0, verbose_name='Total Bookmarks Received')),
                ('followers_count', models.PositiveIntegerField(default=0, verbose_name='Followers Count')),
                ('following_count', models.PositiveIntegerField(default=0, verbose_name='Following Count')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='Last Activity')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Stats',
                'verbose_name_plural': 'User Stats',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Bio')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Location')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('social_links', models.JSONField(blank=True, default=dict, verbose_name='Social Links')),
                ('preferences', models.JSONField(blank=True, default=dict, verbose_name='Preferences')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('post_created', 'Post Created'), ('post_updated', 'Post Updated'), ('post_deleted', 'Post Deleted'), ('comment_added', 'Comment Added'), ('like_added', 'Like Added'), ('bookmark_added', 'Bookmark Added'), ('profile_updated', 'Profile Updated')], max_length=20, verbose_name='Activity Type')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_us_user_id_506163_idx'), models.Index(fields=['activity_type', '-created_at'], name='accounts_us_activit_0ac070_idx')],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='Follower')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='Following')),
            ],
            options={
                'verbose_name': 'Follow',
                'verbose_name_plural': 'Follows',
                'indexes': [models.Index(fields=['follower', '-created_at'], name='accounts_fo_followe_592424_idx'), models.Index(fields=['following', '-created_at'], name='accounts_fo_followi_0cee87_idx')],
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
