# Generated by Django 4.2.20 on 2025-10-25 17:00

import accounts.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_useractivity_user_remove_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='allow_messages',
            field=models.BooleanField(default=True, help_text='Allow other users to send you messages', verbose_name='Allow Messages'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell us about yourself', max_length=500, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='facebook',
            field=models.URLField(blank=True, help_text='Your Facebook profile', verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='github',
            field=models.URLField(blank=True, help_text='Your GitHub profile', verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instagram',
            field=models.URLField(blank=True, help_text='Your Instagram profile', verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Premium membership status', verbose_name='Premium Account'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Account verification status', verbose_name='Verified Account'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Activity'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Your LinkedIn profile', verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, help_text='Your current location', max_length=100, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_public',
            field=models.BooleanField(default=True, help_text='Allow others to view your profile', verbose_name='Public Profile'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='show_email',
            field=models.BooleanField(default=False, help_text='Display email address on profile', verbose_name='Show Email'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twitter',
            field=models.URLField(blank=True, help_text='Your Twitter profile', verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='website',
            field=models.URLField(blank=True, help_text='Your personal website or blog', verbose_name='Website'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='youtube',
            field=models.URLField(blank=True, help_text='Your YouTube channel', verbose_name='YouTube'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Upload your profile picture', null=True, upload_to='avatars/%Y/%m/', validators=[accounts.validators.avatar_validator], verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Your birth date', null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Joined'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Your primary email address', max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, help_text='Your complete name', max_length=150, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Your contact number', max_length=20, validators=[accounts.validators.phone_number_validator], verbose_name='Phone Number'),
        ),
    ]
