# Generated by Django 5.2.4 on 2025-07-18 15:55

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=225, verbose_name="Title")),
                ("slug", models.SlugField(default="", verbose_name="Slug")),
                (
                    "img",
                    models.ImageField(
                        blank=True, upload_to="uploads/%Y/%m/%d", verbose_name="Image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categories",
                "verbose_name_plural": "Categories",
                "ordering": ("title",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=225, verbose_name="Title")),
                ("slug", models.SlugField(default="", verbose_name="Slug")),
                (
                    "img",
                    models.ImageField(
                        blank=True, upload_to="uploads/%Y/%m/%d", verbose_name="Image"
                    ),
                ),
                ("description", markdownx.models.MarkdownxField()),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="Date")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Blogs",
                        to="blog.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "ordering": ("title",),
                "abstract": False,
            },
        ),
    ]
