# Generated by Django 4.2.20 on 2025-10-22 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20251022_1427'),
    ]

    operations = [
        # Remove the old date field
        migrations.RemoveField(
            model_name='blog',
            name='date',
        ),
    ]
