# Generated by Django 4.2.20 on 2025-10-25 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_tag_blog_tags_like_bookmark'),
    ]

    operations = [
    ]
